tango_with_django_project/rango/urls.py
from django.urls import path
from rango import views

app_name = 'rango'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('category/<slug:category_name_slug>/', views.show_category, name='show_category'),
    path('add_category/', views.add_category, name='add_category'),
    path('category/<category_name_slug>/add_page/', views.add_page, name='add_page'),
]

tango_with_django_project/tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

from django.conf import settings
from django.conf.urls.static import static

from rango import views

urlpatterns = [
    path('', views.index, name='index'),
    path('rango/', include('rango.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tango_with_django_project/rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    NAME_MAX_LENGTH = 128

    name = models.CharField(max_length=NAME_MAX_LENGTH, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Page(models.Model):
    TITLE_MAX_LENGTH = 128
    URL_MAX_LENGTH = 200

    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=TITLE_MAX_LENGTH)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # The additional attributes we wish to include.
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)
    def __str__(self):
        return self.user.username

tango_with_django_project/rango/forms.py
from django import forms
from rango.models import Category, Page


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=Category.NAME_MAX_LENGTH, help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=Page.TITLE_MAX_LENGTH, help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200, help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        exclude = ('category',)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        if url and not url.startswith('http://'):
            url = f'http://{url}'
            cleaned_data['url'] = url

        return cleaned_data

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    
    class Meta:
        model = User
        fields = ('username', 'email', 'password',)


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture',)

tango_with_django_project/rango/views.py
from rango.forms import PageForm
from django.shortcuts import render, redirect

from django.http import HttpResponse

from rango.models import Category, Page

from rango.forms import CategoryForm, PageForm

from datetime import datetime

from django.urls import reverse

def index(request):
    request.session.set_test_cookie()
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    context_dict = {'categories': category_list, 'pages': page_list, }

    # Call the helper function to handle the cookies
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']

    # Obtain our Response object early so we can add cookie information.
    response = render(request, 'rango/index.html', context_dict)
    # Return response back to the user, updating any cookies that need changed.
    return response


def about(request):
    if request.session.test_cookie_worked():
        print("TEST COOKIE WORKED!")
        request.session.delete_test_cookie()
    # dictionary for template variables
    context_dict = {'boldmessage': "Hello, this is the most useless page ever"}
    return render(request, 'rango/about.html', context=context_dict)

def show_category(request, category_name_slug):
    # Create a context dictionary which we can pass
    # to the template rendering engine.
    context_dict = {}
    try:
        # Can we find a category name slug with the given name?
        # If we can't, the .get() method raises a DoesNotExist exception.
        # So the .get() method returns one model instance or raises an exception.
        category = Category.objects.get(slug=category_name_slug)
        # Retrieve all of the associated pages.
        # Note that filter() will return a list of page objects or an empty list
        pages = Page.objects.filter(category=category)
        # Adds our results list to the template context under name pages.
        context_dict['pages'] = pages
        # We also add the category object from
        # the database to the context dictionary.
        # We'll use this in the template to verify that the category exists.
        context_dict['category'] = category
        
    except Category.DoesNotExist:
        # We get here if we didn't find the specified category.
        # Don't do anything -
        # the template will display the "no category" message for us.
        context_dict['category'] = None
        context_dict['pages'] = None
        # Go render the response and return it to the client.
    
    return render(request, 'rango/category.html', context_dict)

def add_category(request):
    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)

    if form.is_valid():
        form.save(commit=True)
        # Now that the category is saved
        # We could give a confirmation message
        # But since the most recent category added is on the index page
        # Then we can direct the user back to the index page.
        return index(request)

    else:
        print(form.errors)

    return render(request, 'rango/add_category.html', {'form': form})


def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except:
        category = None

    # You cannot add a page to a Category that does not exist... DM
    if category is None:
        return redirect('/rango/')

    form = PageForm()

    if request.method == 'POST':
        form = PageForm(request.POST)

        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()

                return redirect(reverse('rango:show_category', kwargs={'category_name_slug': category_name_slug}))
        else:
            # This could be better done; for the purposes of TwD, this is fine. DM.
            print(form.errors)

    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context=context_dict)


# Helper Functions======>>>>

def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request,
                                            'last_visit',
                                            str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7],
                                        '%Y-%m-%d %H:%M:%S')
    # If it's been more than a day since the last visit...
    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        #update the last visit cookie now that we have updated the count
        request.session['last_visit'] = str(datetime.now())
    else:
        # Set the last visit cookie
        request.session['last_visit'] = last_visit_cookie
    
    # Update/set the visits cookie
    request.session['visits'] = visits


# A helper method
def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val

tango_with_django_project/templates/rango/about.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    About Rango
{% endblock %}  

{% block body_block %}
    <h1>Rango says here is the about page.</h1>
    <div>
      This tutorial has been put together by Achintya Jha.<br />
      <strong>{{ boldmessage }}</strong><br />
    </div>
    <div>
      <img src="{% static "images/rango.jpg" %}" alt="Stupid GIF">
    </div>
{% endblock %}

tango_with_django_project/templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    Add a Category
{% endblock %}  

{% block body_block %}
        <h1>Add a Category</h1>
        <div>
            <form id="category_form" method="post" action="/rango/add_category/">
                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
                {% for field in form.visible_fields %}
                    {{ field.errors }}
                    {{ field.help_text }}
                    {{ field }}
                {% endfor %}
                <input type="submit" name="submit" value="Create Category">
            </form>
        </div>
{% endblock %}

tango_with_django_project/templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
     Add a Page
{% endblock %}  

{% block body_block %}
    <h1>Add a Page to {{ category.name }}</h1>
    <div>
        <form id="add_page_form" method="post" action="/rango/category/{{ category.slug }}/add_page/">
            {% csrf_token %}
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}
            <input type="submit" name="submit" value="Add Page" />
        </form>
    </div>
{% endblock %}

tango_with_django_project/templates/rango/base.html
<!DOCTYPE html>
{% load static %}
{% load rango_template_tags %}

<html>
<head lang="en">
<meta charset="UTF-8" />
<title>
    Rango -
    {% block title_block %}
    How to Tango with Django!
    {% endblock %}
</title>
</head>
<body>
    <div>
        <!-- Page specific content goes here -->
        {% block body_block %}
            This is body_block's default content.
        {% endblock %}
    </div>
    <div>
        <ul>
            <li><a href="{% url 'rango:add_category' %}">Add a New Category</a></li>
            <li><a href="{% url 'rango:about' %}">About</a></li>
            <li><a href="{% url 'rango:index' %}">Index</a></li>
        </ul>
    </div>
    <div>
        {% block sidebar_block %}
            {% get_category_list category %}
        {% endblock %}
    </div>
</body>
</html>

tango_with_django_project/templates/rango/categories.html
{% for c in categories %}
    {% if c == current_category %}
        <li>
            <strong>
                <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
            </strong>
        </li>
    {% else %}
        <li>
            <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
        </li>
    {% endif %} 
{% endfor %}

tango_with_django_project/templates/rango/category.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    {% if category %}
        {{ category.name }}
        {% else %}
        Unknown Category
    {% endif %}
{% endblock %}

{% block body_block %}
    {% if category %}
        <h1>{{ category.name }}</h1>

        {% if pages %}
        <ul>
            {% for page in pages %}
                <li><a href="{{ page.url }}">{{ page.title }}</a></li>
            {% endfor %}
        </ul>
        {% else %}
            <strong>No pages currently in category.</strong>
        {% endif %}
        <a href="{% url 'rango:add_page' category.slug %}">Add a Page</a>
        <!-- the category.slug is passed through as a parameter to the url template tag -->
    {% else %}
        The specified category does not exist!
    {% endif %}
{% endblock %}

tango_with_django_project/templates/rango/index.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    Homepage
{% endblock %}  

{% block body_block %}
  <h1>Rango says hey there partner!</h1>

  <div>
    {% if categories %}
    <h2>Most Liked Categories</h2>
    <ul>
      {% for category in categories %}
        <!-- Following line changed to add an HTML hyperlink -->
        <li>
          <a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a>
        </li>
      {% endfor %}
    </ul>
    {% else %}
      <strong>There are no categories present.</strong>
    {% endif %}
  </div>

  <p>================================================================</p>

  <div>
    {% if pages %}
    <h2>Most Viewed Pages</h2>
    <ul>
      {% for page in pages %}
        <!-- Following line changed to add an HTML hyperlink -->
        <li>
          <a href="{{ page.url }}">{{ page.title }}</a>
        </li>
      {% endfor %}
    </ul>
    {% else %}
      <strong>There is no such page present.</strong>
    {% endif %}
  </div>

  <div>
    <img src="{% static "images/rango.jpg" %}" alt="Stupid GIF">
  </div>

  <div>
    <p>================================================================</p>
    <p>visits: {{ visits }}</p>
  </div>
    
{% endblock %}